---
title: "data visualization"
---

Charts showing different inflation indicators

There are mainly 3 indicators the US Federal Reserve uses to measure inflation, and hence set interest rates.

1.  Inflation
2.  Core PCE
3.  CPI

```{r, echo=F, message=FALSE}
library(tidyverse)
library(readxl)
```

```{r echo=FALSE}

project_data <- read_excel("data.xlsx", sheet = 2)
cor(project_data$Inflation, project_data$`Core PCE`)
```

```{r, echo  =F}
project_data %>%
  ggplot(aes(x = Inflation, y = `Core PCE`)) +
  geom_point() +
  theme_bw() +
  geom_smooth(method = "lm")
```

```{r, echo=FALSE}
project_data <- read_excel("data.xlsx", sheet = 2)
cor(project_data$Inflation, project_data$`CPI`)
```

```{r, echo=FALSE}
project_data %>%
  ggplot(aes(x = Inflation, y = `CPI`)) +
  geom_point() +
  theme_bw() +
  geom_smooth(method = "lm")
```

Why looking at inflation indicators is important

1.  Interest rate outlook
2.  Interest rates have been higher for longer
3.  Better budgeting
4.  Planning for investments

Important links:

<https://www.cnbc.com/2024/04/16/us-economy-will-see-more-things-break-in-2025-if-rates-stay-high-strategist.html>

<https://www.cnbc.com/2024/04/11/fed-can-start-cutting-interest-rates-by-end-of-2024-imf-managing-director-says.html?&qsearchterm=interest%20rates>

<https://www.cnbc.com/video/2024/04/10/how-marchs-cpi-report-could-impact-the-feds-interest-rate-policy.html?&qsearchterm=interest%20rates>
